### ISSUE TITLE
使用Let's Encrypt申请泛域名证书，降低证书管理复杂度

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/DvcLAB#19]
RT

**Comment by JJLAAA** [comment]
结合[lua-resty-auto-ssl](https://github.com/auto-ssl/lua-resty-auto-ssl)库，完成功能，但是因为使用了生产环境API进行多次测试，现在暂不可申请Let's Encrypt API服务，只写好了Docker Compose Yaml配置文件
```yaml
version: "3"
services:
  # redis对内暴露6379端口
  redis:
    image: redis
    restart: always
    volumes:
      - /opt/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    ports:
      - "61379:6379"
    container_name: or-redis
  openresty:
    image: valian/docker-nginx-auto-ssl
    restart: always
    depends_on:
      - redis
    container_name: openresty
    # 需要修改配置文件
    volumes:
      - /opt/openresty/conf.d/:/etc/nginx/conf.d/
      - /opt/openresty/lua/:/usr/local/openresty/nginx/lua/
      - /opt/dvclab/:/etc/nginx/dist/
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'dvclab.com'
      # 验证--所有服务应该监听80端口
      SITES: '*.dvclab.com=localhost:80'
      RESOLVER_ADDRESS: '8.8.8.8 ipv6=off'
      # rate limit
      LETSENCRYPT_URL: 'https://acme-v02.api.letsencrypt.org/directory'
    ports:
      - "443:443"
      - "80:80"
volumes:
    ssl_data:
```
