### ISSUE TITLE
Wireguard UI的keycloak整合登录

### ISSUE THREAD

**Issue by linstein** [DvcLAB/DvcLAB#41]
目前看到支持Oauth的Wireguard UI:[wg-gen-web](https://github.com/vx3r/wg-gen-web)

**Comment by linstein** [comment]
完成，docker-compose文件如下：
```
version: '3.6'
services:
  wg-gen-web-demo:
    image: vx3r/wg-gen-web:latest
    container_name: wgui
    restart: unless-stopped
    ports:
      - 41197:8080
    environment:
      - WG_CONF_DIR=/data
      - WG_INTERFACE_NAME=wg0.conf
      - OAUTH2_PROVIDER_NAME=oauth2oidc
      - OAUTH2_PROVIDER=https://auth.dvclab.com/auth/realms/${realm}
      - OAUTH2_CLIENT_ID=${client_id}
      - OAUTH2_CLIENT_SECRET=${secret}
      - OAUTH2_REDIRECT_URL=http://dvclab.com:41197
    volumes:
      - /etc/wireguard:/data
```
